[theme]
primaryColor             = "#C84E00"
backgroundColor          = "#F2E8D2"
secondaryBackgroundColor = "#E6D9BD"
textColor                = "#1A0E06"
font                     = "sans serif"

[server]
headless = true
port     = 8501

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
