[theme]
primaryColor             = "#C45000"
backgroundColor          = "#F5EDD8"
secondaryBackgroundColor = "#EDE3CA"
textColor                = "#1A0E06"
font                     = "sans serif"

[server]
headless = true
port     = 8501

[browser]
gatherUsageStats = false
